### ISSUE TITLE
tarfile.ReadError: not an lzma file

### ISSUE THREAD

**Issue by thibault-roux** [helboukkouri/character-bert#25]
When downloading model using `download.py`, there are some trouble. To avoid this, I had to download directly using the URL at the beginning of the script and to decompress it myself in the pretrained-models folder.

```
Traceback (most recent call last):
  File "download.py", line 105, in <module>
    main()
  File "download.py", line 102, in main
    download_model(name=args.model)
  File "download.py", line 79, in download_model
    tar = tarfile.open(file_destination, "r:xz")
  File "/users/troux/.conda/envs/character-bert/lib/python3.8/tarfile.py", line 1621, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/users/troux/.conda/envs/character-bert/lib/python3.8/tarfile.py", line 1734, in xzopen
    raise ReadError("not an lzma file")
tarfile.ReadError: not an lzma file
```

Regards,

**Comment by Sequential-circuits** [comment]
My case too

**Comment by helboukkouri** [comment]
It's fixed, sorry for the delay :)
